#!/usr/bin/env bash

CPU=$(top -bn1 | grep "Cpu(s)" | awk '{print $2}' | cut -d'%' -f1)
CPU_INT=${CPU%.*}

create_bar() {
    local percent=$1
    local bar_length=5
    local filled=$((percent * bar_length / 100))
    local bar=""
    
    for ((i=1; i<=bar_length; i++)); do
        if [ $i -le $filled ]; then
            bar="${bar}▓"
        else
            bar="${bar}░"
        fi
    done
    echo "[$bar]"
}

if [ "$CPU_INT" -lt 50 ]; then
    COLOR="#b4be82"  # Green
    DOT="●"
elif [ "$CPU_INT" -lt 80 ]; then
    COLOR="#e2c792"  # Yellow
    DOT="●"
else
    COLOR="#e27878"  # Red
    DOT="●"
fi

BAR=$(create_bar $CPU_INT)
echo "<span color='$COLOR'>$DOT CPU $BAR</span> ${CPU}%"
