#!/usr/bin/env bash
set -e
source "$(dirname "$0")/../_platform.sh"

echo "Install neovim"

ensure_brew

if command -v nvim &> /dev/null; then
    echo "neovim is already installed. Upgrading..."
    brew upgrade neovim || echo "neovim is already up to date"
else
    brew install neovim
fi
