#!/usr/bin/env bash
set -e

echo "Install i3"
# https://github.com/i3/i3
sudo apt install -y i3 i3lock i3blocks xautolock picom maim xdotool xclip \
                    playerctl pamixer brightnessctl
