#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
	selected=$1
else
	selected=$(find $HOME/code -maxdepth 1 -mindepth 1 -type d | fzf)
fi

if [[ -z "$selected" ]]; then
	exit 0
fi

# Clean the dir name to be valid tmux name by replacing invalid charaters with '_'
selected_name=$(basename $selected | tr ":,. " "____")

switch_to() {
	if [[ -z "$TMUX" ]]; then
		tmux attach-session -t $selected_name
	else
		tmux switch-client -t $selected_name
	fi
}

if tmux has-session -t=$selected_name 2> /dev/null; then
	switch_to
	exit 0
fi

tmux new-session -ds $selected_name -c $selected
switch_to
tmux send-keys -t $selected_name "ready-tmux" ^M
