#!/usr/bin/env bash
set -e

echo "Install brave browser"
# https://brave.com/linux/
command -v curl || {
  echo "Installing curl..."
  sudo apt update && sudo apt install -y curl
}

sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
sudo curl -fsSLo /etc/apt/sources.list.d/brave-browser-release.sources https://brave-browser-apt-release.s3.brave.com/brave-browser.sources
sudo apt update
sudo apt install -y brave-browser
