#!/usr/bin/env bash

DOWNLOAD_FOLDER=/tmp
INSTALL_FOLDER=~/.local/bin
LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | \grep -Po '"tag_name": *"v\K[^"]*')

curl -Lo $DOWNLOAD_FOLDER/lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/download/v${LAZYGIT_VERSION}/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
tar xf $DOWNLOAD_FOLDER/lazygit.tar.gz -C $DOWNLOAD_FOLDER lazygit
sudo install $DOWNLOAD_FOLDER/lazygit -D -t $INSTALL_FOLDER
