#!/usr/bin/env bash

echo "Install neovim"
#https://github.com/neovim/neovim

neovim_dir=$HOME/code/neovim
neovim_version=v0.11.3

git clone -b $neovim_version --depth 1 https://github.com/neovim/neovim.git $neovim_dir
sudo apt install -y gcc make cmake gettext \
                    lua5.1 liblua5.1-0-dev \
                    ripgrep unzip git xclip \
                    fd-find nodejs npm python3-venv python3-pip

cd $neovim_dir
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
