#!/usr/bin/env bash
set -e

echo "Installing python3..."

sudo apt update

command -v python3 || {
  sudo apt install -y python3 
}

command -v python3-venv || {
  sudo apt install -y python3-venv 
}

command -v python3-pip || {
  sudo apt install -y python3-pip 
}

command -v uv || {
  curl -LsSf https://astral.sh/uv/install.sh | sh
}
