#!/usr/bin/env bash

echo "Install fzf"
# https://github.com/junegunn/fzf
fzf_dir=$HOME/code/fzf
git clone --depth 1 https://github.com/junegunn/fzf.git $fzf_dir
$fzf_dir/install --xdg --key-bindings --completion --update-rc


echo "Install bat"
# https://github.com/sharkdp/bat
sudo apt install -y bat


echo "Install task"
# https://taskfile.dev/
sudo sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin


echo "Install zoxide"
# https://github.com/ajeetdsouza/zoxide
curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh


echo "Install bash-completion"
sudo apt install -y bash-completion

echo "Install fd"
sudo apt install -y fd-find
ln -s $(which fdfind) ~/.local/bin/fd
