#!/usr/bin/env bash

echo "Install flatpak"
sudo apt install -y flatpak gnome-software-plugin-flatpak
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

echo "Install zen browser"
flatpak install -y app/app.zen_browser.zen/x86_64/stable
